// <auto-generated />
using System;
using DormitoryManagementSystem.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DormitoryManagementSystem.DataAccess.Migrations
{
    [DbContext(typeof(DormitoryDbContext))]
    [Migration("20260416191040_AddStudentRoleAndUser")]
    partial class AddStudentRoleAndUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.AuditLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ModuleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Building", b =>
                {
                    b.Property<int>("BuildingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BuildingId"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("BuildingName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("BuildingId");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            BuildingId = 1,
                            Address = "OSTİM Kampüs, A Blok",
                            BuildingName = "A Blok"
                        },
                        new
                        {
                            BuildingId = 2,
                            Address = "OSTİM Kampüs, B Blok",
                            BuildingName = "B Blok"
                        },
                        new
                        {
                            BuildingId = 3,
                            Address = "OSTİM Kampüs, C Blok",
                            BuildingName = "C Blok"
                        },
                        new
                        {
                            BuildingId = 4,
                            Address = "OSTİM Kampüs, D Blok",
                            BuildingName = "D Blok"
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("FileType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.HousingRecord", b =>
                {
                    b.Property<int>("HousingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HousingId"));

                    b.Property<DateTime>("CheckInDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HousingStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("HousingId");

                    b.HasIndex("RoomId");

                    b.HasIndex("StudentId");

                    b.ToTable("HousingRecords");

                    b.HasData(
                        new
                        {
                            HousingId = 1,
                            CheckInDate = new DateTime(2025, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HousingStatus = "Active",
                            RoomId = 1,
                            StudentId = 1
                        },
                        new
                        {
                            HousingId = 2,
                            CheckInDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HousingStatus = "Active",
                            RoomId = 1,
                            StudentId = 2
                        },
                        new
                        {
                            HousingId = 3,
                            CheckInDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HousingStatus = "Active",
                            RoomId = 2,
                            StudentId = 3
                        },
                        new
                        {
                            HousingId = 4,
                            CheckInDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HousingStatus = "Active",
                            RoomId = 2,
                            StudentId = 4
                        },
                        new
                        {
                            HousingId = 5,
                            CheckInDate = new DateTime(2025, 9, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CheckOutDate = new DateTime(2026, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HousingStatus = "CheckedOut",
                            RoomId = 3,
                            StudentId = 5
                        },
                        new
                        {
                            HousingId = 6,
                            CheckInDate = new DateTime(2025, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HousingStatus = "Active",
                            RoomId = 3,
                            StudentId = 6
                        },
                        new
                        {
                            HousingId = 7,
                            CheckInDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HousingStatus = "Active",
                            RoomId = 3,
                            StudentId = 7
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("AssignedStaffId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("IssueTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Medium");

                    b.Property<int>("ReportedByStudentId")
                        .HasColumnType("int");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.HasKey("RequestId");

                    b.HasIndex("ReportedByStudentId");

                    b.HasIndex("RoomId");

                    b.ToTable("MaintenanceRequests");

                    b.HasData(
                        new
                        {
                            RequestId = 1,
                            CreatedAt = new DateTime(2025, 10, 8, 10, 30, 0, 0, DateTimeKind.Unspecified),
                            IssueTitle = "Musluk sızıntısı var",
                            Priority = "High",
                            ReportedByStudentId = 1,
                            RoomId = 1,
                            Status = "Assigned"
                        },
                        new
                        {
                            RequestId = 2,
                            CreatedAt = new DateTime(2025, 10, 15, 14, 15, 0, 0, DateTimeKind.Unspecified),
                            IssueTitle = "Isıtıcı çalışmıyor",
                            Priority = "Medium",
                            ReportedByStudentId = 6,
                            RoomId = 3,
                            Status = "Open"
                        },
                        new
                        {
                            RequestId = 3,
                            CompletedAt = new DateTime(2025, 9, 5, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedAt = new DateTime(2025, 9, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IssueTitle = "Pencere camı çatlak",
                            Priority = "Low",
                            ReportedByStudentId = 3,
                            RoomId = 2,
                            Status = "Closed"
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Info");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");

                    b.HasData(
                        new
                        {
                            NotificationId = 1,
                            CreatedAt = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Message = "Aylık yurt doluluk raporu hazırlandı.",
                            Type = "Info",
                            UserId = 1
                        },
                        new
                        {
                            NotificationId = 2,
                            CreatedAt = new DateTime(2026, 4, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            IsRead = false,
                            Message = "2 adet açık bakım talebi bulunmakta.",
                            Type = "Warning",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Semester")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("PaymentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = 1,
                            Amount = 2500m,
                            DueDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidDate = new DateTime(2025, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "2025-2026 Güz",
                            Status = "Paid",
                            StudentId = 1
                        },
                        new
                        {
                            PaymentId = 2,
                            Amount = 2500m,
                            DueDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidDate = new DateTime(2025, 10, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "2025-2026 Güz",
                            Status = "Paid",
                            StudentId = 2
                        },
                        new
                        {
                            PaymentId = 3,
                            Amount = 2500m,
                            DueDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "2025-2026 Güz",
                            Status = "Pending",
                            StudentId = 3
                        },
                        new
                        {
                            PaymentId = 4,
                            Amount = 2500m,
                            DueDate = new DateTime(2025, 10, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "2025-2026 Güz",
                            Status = "Overdue",
                            StudentId = 4
                        },
                        new
                        {
                            PaymentId = 5,
                            Amount = 2750m,
                            DueDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidDate = new DateTime(2026, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "2025-2026 Bahar",
                            Status = "Paid",
                            StudentId = 1
                        },
                        new
                        {
                            PaymentId = 6,
                            Amount = 2750m,
                            DueDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "2025-2026 Bahar",
                            Status = "Pending",
                            StudentId = 2
                        },
                        new
                        {
                            PaymentId = 7,
                            Amount = 2750m,
                            DueDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaidDate = new DateTime(2026, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "2025-2026 Bahar",
                            Status = "Paid",
                            StudentId = 6
                        },
                        new
                        {
                            PaymentId = 8,
                            Amount = 2750m,
                            DueDate = new DateTime(2026, 2, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Semester = "2025-2026 Bahar",
                            Status = "Pending",
                            StudentId = 7
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Penalty", b =>
                {
                    b.Property<int>("PenaltyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PenaltyId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("PenaltyId");

                    b.HasIndex("StudentId");

                    b.ToTable("Penalties");

                    b.HasData(
                        new
                        {
                            PenaltyId = 1,
                            Amount = 125m,
                            DueDate = new DateTime(2025, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Geç ödeme gecikme cezası",
                            Status = "Pending",
                            StudentId = 4
                        },
                        new
                        {
                            PenaltyId = 2,
                            Amount = 250m,
                            DueDate = new DateTime(2025, 12, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Reason = "Yurt kuralları ihlali (gürültü)",
                            Status = "Pending",
                            StudentId = 3
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Description = "Sistem Yöneticisi",
                            RoleName = "SystemAdmin"
                        },
                        new
                        {
                            RoleId = 2,
                            Description = "Yurt Müdürü",
                            RoleName = "DormitoryManager"
                        },
                        new
                        {
                            RoleId = 3,
                            Description = "Mali İşler Personeli",
                            RoleName = "FinanceOfficer"
                        },
                        new
                        {
                            RoleId = 4,
                            Description = "Yurt Personeli",
                            RoleName = "DormitoryStaff"
                        },
                        new
                        {
                            RoleId = 5,
                            Description = "Öğrenci Kullanıcı",
                            RoleName = "Student"
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<int>("FloorNo")
                        .HasColumnType("int");

                    b.Property<int>("OccupiedBeds")
                        .HasColumnType("int");

                    b.Property<string>("RoomNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RoomType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("Available");

                    b.HasKey("RoomId");

                    b.HasIndex("BuildingId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            BuildingId = 1,
                            Capacity = 2,
                            FloorNo = 2,
                            OccupiedBeds = 2,
                            RoomNumber = "A-203",
                            RoomType = "Double",
                            Status = "Full"
                        },
                        new
                        {
                            RoomId = 2,
                            BuildingId = 1,
                            Capacity = 2,
                            FloorNo = 2,
                            OccupiedBeds = 2,
                            RoomNumber = "A-204",
                            RoomType = "Double",
                            Status = "Full"
                        },
                        new
                        {
                            RoomId = 3,
                            BuildingId = 2,
                            Capacity = 3,
                            FloorNo = 1,
                            OccupiedBeds = 2,
                            RoomNumber = "B-113",
                            RoomType = "Triple",
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 4,
                            BuildingId = 2,
                            Capacity = 2,
                            FloorNo = 1,
                            OccupiedBeds = 0,
                            RoomNumber = "B-115",
                            RoomType = "Double",
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 5,
                            BuildingId = 3,
                            Capacity = 4,
                            FloorNo = 3,
                            OccupiedBeds = 0,
                            RoomNumber = "C-307",
                            RoomType = "Quad",
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 6,
                            BuildingId = 3,
                            Capacity = 2,
                            FloorNo = 3,
                            OccupiedBeds = 0,
                            RoomNumber = "C-310",
                            RoomType = "Double",
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 7,
                            BuildingId = 4,
                            Capacity = 3,
                            FloorNo = 1,
                            OccupiedBeds = 0,
                            RoomNumber = "D-104",
                            RoomType = "Triple",
                            Status = "Available"
                        },
                        new
                        {
                            RoomId = 8,
                            BuildingId = 4,
                            Capacity = 2,
                            FloorNo = 1,
                            OccupiedBeds = 0,
                            RoomNumber = "D-109",
                            RoomType = "Double",
                            Status = "Available"
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentNumber")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            StudentId = 1,
                            Email = "ayse.yilmaz@student.ostimteknik.edu.tr",
                            FullName = "Ayşe Yılmaz",
                            Phone = "05551234567",
                            Program = "Computer Engineering",
                            Status = "Active",
                            StudentNumber = "2026001",
                            Year = 2
                        },
                        new
                        {
                            StudentId = 2,
                            Email = "mehmet.kaya@student.ostimteknik.edu.tr",
                            FullName = "Mehmet Kaya",
                            Phone = "05552345678",
                            Program = "Software Engineering",
                            Status = "Active",
                            StudentNumber = "2026012",
                            Year = 1
                        },
                        new
                        {
                            StudentId = 3,
                            Email = "elif.demir@student.ostimteknik.edu.tr",
                            FullName = "Elif Demir",
                            Phone = "05553456789",
                            Program = "Industrial Engineering",
                            Status = "Active",
                            StudentNumber = "2026033",
                            Year = 3
                        },
                        new
                        {
                            StudentId = 4,
                            Email = "burak.sahin@student.ostimteknik.edu.tr",
                            FullName = "Burak Şahin",
                            Phone = "05554567890",
                            Program = "Mechanical Engineering",
                            Status = "Active",
                            StudentNumber = "2026060",
                            Year = 4
                        },
                        new
                        {
                            StudentId = 5,
                            Email = "zeynep.arslan@student.ostimteknik.edu.tr",
                            FullName = "Zeynep Arslan",
                            Phone = "05555678901",
                            Program = "Civil Engineering",
                            Status = "Left",
                            StudentNumber = "2026088",
                            Year = 2
                        },
                        new
                        {
                            StudentId = 6,
                            Email = "deniz.ozturk@student.ostimteknik.edu.tr",
                            FullName = "Deniz Öztürk",
                            Phone = "05556789012",
                            Program = "Electrical Engineering",
                            Status = "Active",
                            StudentNumber = "2026105",
                            Year = 1
                        },
                        new
                        {
                            StudentId = 7,
                            Email = "canan.aydin@student.ostimteknik.edu.tr",
                            FullName = "Canan Aydın",
                            Phone = "05557890123",
                            Program = "Software Engineering",
                            Status = "Active",
                            StudentNumber = "2026122",
                            Year = 3
                        },
                        new
                        {
                            StudentId = 8,
                            Email = "emre.celik@student.ostimteknik.edu.tr",
                            FullName = "Emre Çelik",
                            Phone = "05558901234",
                            Program = "Computer Engineering",
                            Status = "Active",
                            StudentNumber = "2026140",
                            Year = 2
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            FullName = "Sistem Yöneticisi",
                            IsActive = true,
                            PasswordHash = "PrP+ZrMeO00Q+nC1ytSccRIpSvauTkdqHEBRVdRaoSE=",
                            RoleId = 1,
                            Username = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            FullName = "Öğrenci Kullanıcı",
                            IsActive = true,
                            PasswordHash = "yyQzBz7bJcp38ERdzb1+fFaBlu7xzVTacijd0ickDi4=",
                            RoleId = 5,
                            Username = "student"
                        });
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.AuditLog", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Document", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.HousingRecord", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Room", "Room")
                        .WithMany("HousingRecords")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Student", "Student")
                        .WithMany("HousingRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.MaintenanceRequest", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Student", "ReportedByStudent")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("ReportedByStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Room", "Room")
                        .WithMany("MaintenanceRequests")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReportedByStudent");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Notification", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Payment", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Penalty", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Student", "Student")
                        .WithMany("Penalties")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Room", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Building", "Building")
                        .WithMany("Rooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.User", b =>
                {
                    b.HasOne("DormitoryManagementSystem.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Building", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Room", b =>
                {
                    b.Navigation("HousingRecords");

                    b.Navigation("MaintenanceRequests");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.Student", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("HousingRecords");

                    b.Navigation("MaintenanceRequests");

                    b.Navigation("Payments");

                    b.Navigation("Penalties");
                });

            modelBuilder.Entity("DormitoryManagementSystem.Domain.Entities.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("Notifications");
                });
#pragma warning restore 612, 618
        }
    }
}
